from conf.env import env

SHIP_TO_MOTHERSHIP_NUMBER = env.int("SHIP_TO_MOTHERSHIP_NUMBER", 3)
MAXIMUM_SHIP_TO_MOTHERSHIP_CAPACITY = env.int("MAXIMUM_SHIP_TO_MOTHERSHIP_CAPACITY", 9)
CREWMEMBER_TO_SHIP_NUMBER = env.int("CREWMEMBER_TO_SHIP_NUMBER", 3)
MAXIMUM_CREWMEMBER_TO_SHIP_CAPACITY = env.int("MAXIMUM_CREWMEMBER_TO_SHIP_CAPACITY", 5)
