from conf.env import env

MAXIMUM_SHIP_NUMBER = env.int("MAXIMUM_SHIP_NUMBER", 9)
SHIP_TO_MOTHERSHIP_NUMBER = env.int("SHIP_TO_MOTHERSHIP_NUMBER", 3)
MAXIMUM_CREWMEMBER_NUMBER = env.int("MAXIMUM_CREWMEMBER_NUMBER", 5)
CREWMEMBER_TO_SHIP_NUMBER = env.int("CREWMEMBER_TO_SHIP_NUMBER", 3)
